"""Initial migration with users and income_taxes tables

Revision ID: 07af927ecd81
Revises: 
Create Date: 2025-12-13 14:44:56.121639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07af927ecd81'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('income_taxes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filing_state', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('income_taxes', schema=None) as batch_op:
        batch_op.drop_column('filing_state')

    # ### end Alembic commands ###
