"""add_iso_options_and_budget_tables

Revision ID: 1b31dc368977
Revises: 2dade53f88fc
Create Date: 2025-12-13 15:53:08.389992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b31dc368977'
down_revision: Union[str, Sequence[str], None] = '2dade53f88fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('income_taxes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('iso_shares_exercised', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('iso_strike_price', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('iso_fmv_at_exercise', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('income_taxes', schema=None) as batch_op:
        batch_op.drop_column('iso_fmv_at_exercise')
        batch_op.drop_column('iso_strike_price')
        batch_op.drop_column('iso_shares_exercised')

    # ### end Alembic commands ###
